# Clippy configuration for MY CODE

# Allow some lints that are too pedantic for our use case
allowed-wildcard-imports = []

# Prefer these alternatives
too-many-arguments-threshold = 8
type-complexity-threshold = 300
